[project]
name = "gansekou-backend"
version = "1.0.0"
description = "Backend officiel de GANSEKOU"
requires-python = ">=3.13"
dependencies = [
    "fastapi==0.115.6",
    "pydantic==2.10.4",
    "pydantic-settings==2.7.0",
    "email-validator==2.2.0",
    "python-multipart==0.0.20",
    "httpx==0.28.1"
]

[dependency-groups]
dev = [
    "workers-py",
    "workers-runtime-sdk"
]
