"""add adaptive learning

Revision ID: 614a484a167d
Revises: 916cb61fee02
Create Date: 2026-05-19 13:26:55.953778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614a484a167d'
down_revision: Union[str, Sequence[str], None] = '916cb61fee02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_skill_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=150), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', 'level_id', 'skill_name', name='uq_student_skill_progress')
    )
    op.create_index(op.f('ix_student_skill_progress_level_id'), 'student_skill_progress', ['level_id'], unique=False)
    op.create_index(op.f('ix_student_skill_progress_skill_name'), 'student_skill_progress', ['skill_name'], unique=False)
    op.create_index(op.f('ix_student_skill_progress_status'), 'student_skill_progress', ['status'], unique=False)
    op.create_index(op.f('ix_student_skill_progress_student_id'), 'student_skill_progress', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_skill_progress_subject_id'), 'student_skill_progress', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_skill_progress_subject_id'), table_name='student_skill_progress')
    op.drop_index(op.f('ix_student_skill_progress_student_id'), table_name='student_skill_progress')
    op.drop_index(op.f('ix_student_skill_progress_status'), table_name='student_skill_progress')
    op.drop_index(op.f('ix_student_skill_progress_skill_name'), table_name='student_skill_progress')
    op.drop_index(op.f('ix_student_skill_progress_level_id'), table_name='student_skill_progress')
    op.drop_table('student_skill_progress')
    # ### end Alembic commands ###
