"""add quiz engine

Revision ID: 916cb61fee02
Revises: e25c07bdf26b
Create Date: 2026-05-19 12:58:37.069907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916cb61fee02'
down_revision: Union[str, Sequence[str], None] = 'e25c07bdf26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('difficulty_level', sa.String(length=30), nullable=True),
    sa.Column('quiz_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_randomized', sa.Boolean(), nullable=False),
    sa.Column('allow_retry', sa.Boolean(), nullable=False),
    sa.Column('passing_score', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_author_id'), 'quizzes', ['author_id'], unique=False)
    op.create_index(op.f('ix_quizzes_content_id'), 'quizzes', ['content_id'], unique=False)
    op.create_index(op.f('ix_quizzes_language'), 'quizzes', ['language'], unique=False)
    op.create_index(op.f('ix_quizzes_level_id'), 'quizzes', ['level_id'], unique=False)
    op.create_index(op.f('ix_quizzes_quiz_type'), 'quizzes', ['quiz_type'], unique=False)
    op.create_index(op.f('ix_quizzes_status'), 'quizzes', ['status'], unique=False)
    op.create_index(op.f('ix_quizzes_subject_id'), 'quizzes', ['subject_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_student_id'), 'quiz_attempts', ['student_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_image_url', sa.String(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_quiz_id'), 'quiz_questions', ['quiz_id'], unique=False)
    op.create_table('quiz_choices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('choice_text', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_choices_question_id'), 'quiz_choices', ['question_id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_choice_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['selected_choice_id'], ['quiz_choices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_answers_attempt_id'), 'quiz_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_question_id'), 'quiz_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_selected_choice_id'), 'quiz_answers', ['selected_choice_id'], unique=False)
    op.add_column('content_translations', sa.Column('short_description', sa.Text(), nullable=True))
    op.add_column('content_translations', sa.Column('objectives', sa.Text(), nullable=True))
    op.add_column('content_translations', sa.Column('prerequisites', sa.Text(), nullable=True))
    op.add_column('content_translations', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('content_translations', sa.Column('keywords', sa.Text(), nullable=True))
    op.create_index(op.f('ix_content_translations_content_id'), 'content_translations', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_translations_language'), 'content_translations', ['language'], unique=False)
    op.add_column('contents', sa.Column('video_url', sa.String(), nullable=True))
    op.add_column('contents', sa.Column('audio_url', sa.String(), nullable=True))
    op.add_column('contents', sa.Column('external_url', sa.String(), nullable=True))
    op.add_column('contents', sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('contents', sa.Column('difficulty_level', sa.String(length=30), nullable=True))
    op.add_column('contents', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('contents', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.add_column('contents', sa.Column('is_downloadable', sa.Boolean(), nullable=False))
    op.add_column('contents', sa.Column('allow_comments', sa.Boolean(), nullable=False))
    op.add_column('contents', sa.Column('allow_ai_summary', sa.Boolean(), nullable=False))
    op.add_column('contents', sa.Column('total_views', sa.Integer(), nullable=False))
    op.add_column('contents', sa.Column('total_downloads', sa.Integer(), nullable=False))
    op.add_column('contents', sa.Column('total_likes', sa.Integer(), nullable=False))
    op.add_column('contents', sa.Column('total_shares', sa.Integer(), nullable=False))
    op.add_column('contents', sa.Column('average_rating', sa.Integer(), nullable=True))
    op.add_column('contents', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_contents_author_id'), 'contents', ['author_id'], unique=False)
    op.create_index(op.f('ix_contents_content_type'), 'contents', ['content_type'], unique=False)
    op.create_index(op.f('ix_contents_level_id'), 'contents', ['level_id'], unique=False)
    op.create_index(op.f('ix_contents_specialty_id'), 'contents', ['specialty_id'], unique=False)
    op.create_index(op.f('ix_contents_status'), 'contents', ['status'], unique=False)
    op.create_index(op.f('ix_contents_subject_id'), 'contents', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_subject_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_status'), table_name='contents')
    op.drop_index(op.f('ix_contents_specialty_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_level_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_content_type'), table_name='contents')
    op.drop_index(op.f('ix_contents_author_id'), table_name='contents')
    op.drop_column('contents', 'published_at')
    op.drop_column('contents', 'average_rating')
    op.drop_column('contents', 'total_shares')
    op.drop_column('contents', 'total_likes')
    op.drop_column('contents', 'total_downloads')
    op.drop_column('contents', 'total_views')
    op.drop_column('contents', 'allow_ai_summary')
    op.drop_column('contents', 'allow_comments')
    op.drop_column('contents', 'is_downloadable')
    op.drop_column('contents', 'is_featured')
    op.drop_column('contents', 'tags')
    op.drop_column('contents', 'difficulty_level')
    op.drop_column('contents', 'estimated_duration_minutes')
    op.drop_column('contents', 'external_url')
    op.drop_column('contents', 'audio_url')
    op.drop_column('contents', 'video_url')
    op.drop_index(op.f('ix_content_translations_language'), table_name='content_translations')
    op.drop_index(op.f('ix_content_translations_content_id'), table_name='content_translations')
    op.drop_column('content_translations', 'keywords')
    op.drop_column('content_translations', 'ai_summary')
    op.drop_column('content_translations', 'prerequisites')
    op.drop_column('content_translations', 'objectives')
    op.drop_column('content_translations', 'short_description')
    op.drop_index(op.f('ix_quiz_answers_selected_choice_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_question_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_attempt_id'), table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index(op.f('ix_quiz_choices_question_id'), table_name='quiz_choices')
    op.drop_table('quiz_choices')
    op.drop_index(op.f('ix_quiz_questions_quiz_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_quiz_attempts_student_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_quizzes_subject_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_status'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_quiz_type'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_level_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_language'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_content_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_author_id'), table_name='quizzes')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
