"""add content relations table

Revision ID: a261ceb5ac95
Revises: 7f4d2c9b1a6e
Create Date: 2026-07-31 06:46:22.661723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a261ceb5ac95"
down_revision: Union[str, Sequence[str], None] = "7f4d2c9b1a6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_relations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("parent_content_id", sa.UUID(), nullable=False),
        sa.Column("child_content_id", sa.UUID(), nullable=False),
        sa.Column("relation_type", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["child_content_id"],
            ["contents.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_content_id"],
            ["contents.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parent_content_id",
            "child_content_id",
            "relation_type",
            name="uq_content_relation",
        ),
    )

    op.create_index(
        op.f("ix_content_relations_child_content_id"),
        "content_relations",
        ["child_content_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_content_relations_parent_content_id"),
        "content_relations",
        ["parent_content_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_content_relations_relation_type"),
        "content_relations",
        ["relation_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_content_relations_relation_type"),
        table_name="content_relations",
    )

    op.drop_index(
        op.f("ix_content_relations_parent_content_id"),
        table_name="content_relations",
    )

    op.drop_index(
        op.f("ix_content_relations_child_content_id"),
        table_name="content_relations",
    )

    op.drop_table("content_relations")
    # ### end Alembic commands ###
