"""add study planner

Revision ID: b797657c76d4
Revises: 83093594a833
Create Date: 2026-05-19 13:57:31.892567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b797657c76d4'
down_revision: Union[str, Sequence[str], None] = '83093594a833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plans_language'), 'study_plans', ['language'], unique=False)
    op.create_index(op.f('ix_study_plans_plan_type'), 'study_plans', ['plan_type'], unique=False)
    op.create_index(op.f('ix_study_plans_status'), 'study_plans', ['status'], unique=False)
    op.create_index(op.f('ix_study_plans_student_id'), 'study_plans', ['student_id'], unique=False)
    op.create_table('study_plan_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_plan_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('level_id', sa.UUID(), nullable=True),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('quiz_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('skill_name', sa.String(length=150), nullable=True),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plan_items_content_id'), 'study_plan_items', ['content_id'], unique=False)
    op.create_index(op.f('ix_study_plan_items_is_completed'), 'study_plan_items', ['is_completed'], unique=False)
    op.create_index(op.f('ix_study_plan_items_item_type'), 'study_plan_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_study_plan_items_level_id'), 'study_plan_items', ['level_id'], unique=False)
    op.create_index(op.f('ix_study_plan_items_priority'), 'study_plan_items', ['priority'], unique=False)
    op.create_index(op.f('ix_study_plan_items_quiz_id'), 'study_plan_items', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_study_plan_items_scheduled_for'), 'study_plan_items', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_study_plan_items_skill_name'), 'study_plan_items', ['skill_name'], unique=False)
    op.create_index(op.f('ix_study_plan_items_study_plan_id'), 'study_plan_items', ['study_plan_id'], unique=False)
    op.create_index(op.f('ix_study_plan_items_subject_id'), 'study_plan_items', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_plan_items_subject_id'), table_name='study_plan_items')
    op.drop_index(op.f('ix_study_plan_items_study_plan_id'), table_name='study_plan_items')
    op.drop_index(op.f('ix_study_plan_items_skill_name'), table_name='study_plan_items')
    op.drop_index(op.f('ix_study_plan_items_scheduled_for'), table_name='study_plan_items')
    op.drop_index(op.f('ix_study_plan_items_quiz_id'), table_name='study_plan_items')
    op.drop_index(op.f('ix_study_plan_items_priority'), table_name='study_plan_items')
    op.drop_index(op.f('ix_study_plan_items_level_id'), table_name='study_plan_items')
    op.drop_index(op.f('ix_study_plan_items_item_type'), table_name='study_plan_items')
    op.drop_index(op.f('ix_study_plan_items_is_completed'), table_name='study_plan_items')
    op.drop_index(op.f('ix_study_plan_items_content_id'), table_name='study_plan_items')
    op.drop_table('study_plan_items')
    op.drop_index(op.f('ix_study_plans_student_id'), table_name='study_plans')
    op.drop_index(op.f('ix_study_plans_status'), table_name='study_plans')
    op.drop_index(op.f('ix_study_plans_plan_type'), table_name='study_plans')
    op.drop_index(op.f('ix_study_plans_language'), table_name='study_plans')
    op.drop_table('study_plans')
    # ### end Alembic commands ###
