"""add content progress favorites ratings

Revision ID: bf31ab8350b6
Revises: b797657c76d4
Create Date: 2026-05-19 14:15:16.250541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf31ab8350b6'
down_revision: Union[str, Sequence[str], None] = 'b797657c76d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'content_id', name='uq_student_content_favorite')
    )
    op.create_index(op.f('ix_content_favorites_content_id'), 'content_favorites', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_favorites_student_id'), 'content_favorites', ['student_id'], unique=False)
    op.create_table('content_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('is_started', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'content_id', name='uq_student_content_progress')
    )
    op.create_index(op.f('ix_content_progress_content_id'), 'content_progress', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_progress_is_completed'), 'content_progress', ['is_completed'], unique=False)
    op.create_index(op.f('ix_content_progress_is_started'), 'content_progress', ['is_started'], unique=False)
    op.create_index(op.f('ix_content_progress_student_id'), 'content_progress', ['student_id'], unique=False)
    op.create_table('content_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'content_id', name='uq_student_content_rating')
    )
    op.create_index(op.f('ix_content_ratings_content_id'), 'content_ratings', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_ratings_student_id'), 'content_ratings', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_ratings_student_id'), table_name='content_ratings')
    op.drop_index(op.f('ix_content_ratings_content_id'), table_name='content_ratings')
    op.drop_table('content_ratings')
    op.drop_index(op.f('ix_content_progress_student_id'), table_name='content_progress')
    op.drop_index(op.f('ix_content_progress_is_started'), table_name='content_progress')
    op.drop_index(op.f('ix_content_progress_is_completed'), table_name='content_progress')
    op.drop_index(op.f('ix_content_progress_content_id'), table_name='content_progress')
    op.drop_table('content_progress')
    op.drop_index(op.f('ix_content_favorites_student_id'), table_name='content_favorites')
    op.drop_index(op.f('ix_content_favorites_content_id'), table_name='content_favorites')
    op.drop_table('content_favorites')
    # ### end Alembic commands ###
