"""clean teacher ai migration

Revision ID: e25c07bdf26b
Revises: 028842b0dbc6
Create Date: 2026-05-19 11:52:48.978820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25c07bdf26b'
down_revision: Union[str, Sequence[str], None] = '028842b0dbc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'subject_id', name='uq_teacher_subject')
    )
    op.create_index(op.f('ix_ai_answers_question_id'), 'ai_answers', ['question_id'], unique=False)
    op.drop_constraint(op.f('ai_cache_question_hash_key'), 'ai_cache', type_='unique')
    op.create_index(op.f('ix_ai_cache_language'), 'ai_cache', ['language'], unique=False)
    op.create_index(op.f('ix_ai_cache_question_hash'), 'ai_cache', ['question_hash'], unique=True)
    op.create_index(op.f('ix_ai_usage_logs_usage_date'), 'ai_usage_logs', ['usage_date'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_user_id'), 'ai_usage_logs', ['user_id'], unique=False)
    op.create_unique_constraint('uq_ai_usage_user_date', 'ai_usage_logs', ['user_id', 'usage_date'])
    op.add_column('student_questions', sa.Column('assigned_teacher_id', sa.UUID(), nullable=True))
    op.add_column('student_questions', sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_student_questions_assigned_teacher_id'), 'student_questions', ['assigned_teacher_id'], unique=False)
    op.create_index(op.f('ix_student_questions_status'), 'student_questions', ['status'], unique=False)
    op.create_index(op.f('ix_student_questions_student_id'), 'student_questions', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_questions_subject_id'), 'student_questions', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'student_questions', 'users', ['assigned_teacher_id'], ['id'])
    op.create_index(op.f('ix_teacher_answers_question_id'), 'teacher_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_teacher_answers_status'), 'teacher_answers', ['status'], unique=False)
    op.create_index(op.f('ix_teacher_answers_teacher_id'), 'teacher_answers', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_answers_teacher_id'), table_name='teacher_answers')
    op.drop_index(op.f('ix_teacher_answers_status'), table_name='teacher_answers')
    op.drop_index(op.f('ix_teacher_answers_question_id'), table_name='teacher_answers')
    op.drop_constraint(None, 'student_questions', type_='foreignkey')
    op.drop_index(op.f('ix_student_questions_subject_id'), table_name='student_questions')
    op.drop_index(op.f('ix_student_questions_student_id'), table_name='student_questions')
    op.drop_index(op.f('ix_student_questions_status'), table_name='student_questions')
    op.drop_index(op.f('ix_student_questions_assigned_teacher_id'), table_name='student_questions')
    op.drop_column('student_questions', 'answered_at')
    op.drop_column('student_questions', 'assigned_teacher_id')
    op.drop_constraint('uq_ai_usage_user_date', 'ai_usage_logs', type_='unique')
    op.drop_index(op.f('ix_ai_usage_logs_user_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_usage_date'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_cache_question_hash'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_language'), table_name='ai_cache')
    op.create_unique_constraint(op.f('ai_cache_question_hash_key'), 'ai_cache', ['question_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_ai_answers_question_id'), table_name='ai_answers')
    op.drop_table('teacher_subjects')
    # ### end Alembic commands ###
